### ISSUE TITLE
Creating empty HTML and CSS files

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [lauraramirez220612/TeamFourHYF#21] opened 2021-04-19 07:25 UTC
HTML and CSS file needed to be created and left empty till the writing code stage

**Comment by danielhalasz** [comment] 2021-04-19 08:32
this is a duplicate of the issue
https://github.com/lauraramirez220612/TeamFourHYF/issues/9

**Comment by Moamin-AbuEwaida** [comment] 2021-04-19 10:43
ooh, I'll close this one then @danielhalasz

**Closed** 2021-04-19 11:29 UTC
Labels: documentation
